### ISSUE TITLE
No documentation or settings

### ISSUE THREAD

**Issue by doctord1** [Kendysond/Drupal-Ubercart-Paystack#1]
hello, nice wrk here , but how do you configure the module, ad how do you use it? it does not show up under payment methods, alongside cod and check as i wouldhave espected,and there is just no way to save any settings, how does paystack know which merchant is being paid

**Comment by Kendysond** [comment]
Hello @doctord1, 

The module is dependent on the ubercart module on drupal, you're to paste the uc_paystack folder in the ubercart/payment/ folder. 

I hope this helps. 
<img width="394" alt="screen shot 2017-03-20 at 9 49 09 pm" src="https://cloud.githubusercontent.com/assets/5365813/24121076/2ec01b5c-0db7-11e7-9e1f-fcd16b3edffd.png">

**Comment by doctord1** [comment]
thanks for the clarification, it works excellently, but there is a problem i keep getting, an error about duplicate references, in the paystack documentation, it says you are never supposed to send the same references twice, how do i work around that

**Comment by amodu** [comment]
Hello every one
After installing uc_paystack module, I test run it, it processes payment successfully but redirects to an error page. the error message is:

Not Found
The requested URL /cart/paystack/complete was not found on this server.

The url is stated 3 times in the  uc_paystack_module file.
please kindly assist in pointing me in the right solution to solve this problem.
Thank you.
